[package]
name = "screenshot"
description = "Screenshot capture utility."
version = "0.3.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
failure = "0.1"
structopt = "0.2"
time = "0.1"
x11 = { version = "2.18", features = ["xlib"] }
