[package]
name = "screenshot"
description = "Screenshot capture utility."
version = "0.3.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[workspace]
members = [".", "imlib2", "imlib2/imlib2-sys", "xlib"]

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
failure = "0.1"
png = "0.12"
imlib2 = { path = "imlib2" }
structopt = "0.2"
time = "0.1"
xlib = { path = "xlib" }
