[package]
name = "leanshot"
version = "0.1.0"
description = "Takes screenshots."
license-file = "LICENSE"
repository = "https://github.com/iptq/screenshot"
authors = ["Michael Zhang <failed.down@gmail.com>"]
build = "src/build.rs"

[dependencies]
clap = "2.31.2"
cairo-rs = { version = "0.4.1", features = ["png"] }
failure = "0.1.1"
gdk = "0.8.0"
gdk-pixbuf = "0.4.0"
gio = "0.4.0"
gtk = { version = "0.4.1", features = ["v3_16"] }
time = "0.1.40"
