[package]
name = "imlib2"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
failure = "0.1"
imlib2-sys = { path = "imlib2-sys" }
x11 = { version = "2.18", features = ["xlib"] }
