[package]
name = "imlib2"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[dependencies]
failure = "0.1"
imlib2-sys = { path = "imlib2-sys" }
leanshot_xlib = { path = "../xlib" }
